package com.cloud.askwalking.gateway.manager.model;

import java.io.Serializable;
import java.util.Date;

public class SaasConfigDO implements Serializable {
    /**
     * 
     * 表字段 : gw_saas_config.id
     */
    private String id;

    /**
     * 接入商授权id
     * 表字段 : gw_saas_config.open_id
     */
    private String openId;

    /**
     * 接入商名称
     * 表字段 : gw_saas_config.open_name
     */
    private String openName;

    /**
     * 内部私钥
     * 表字段 : gw_saas_config.private_key
     */
    private String privateKey;

    /**
     * 内部公钥
     * 表字段 : gw_saas_config.public_key
     */
    private String publicKey;

    /**
     * 外部公钥
     * 表字段 : gw_saas_config.outer_public_key
     */
    private String outerPublicKey;

    /**
     * 接入商状态，1-准入/2-禁止
     * 表字段 : gw_saas_config.status
     */
    private Byte status;

    /**
     * 到期时间
     * 表字段 : gw_saas_config.expire_time
     */
    private Date expireTime;

    /**
     * 0-未删除,1-已删除
     * 表字段 : gw_saas_config.delete_flag
     */
    private Boolean deleteFlag;

    /**
     * 操作人
     * 表字段 : gw_saas_config.operator
     */
    private String operator;

    /**
     * 更新时间
     * 表字段 : gw_saas_config.update_time
     */
    private Date updateTime;

    /**
     * 创建时间
     * 表字段 : gw_saas_config.create_time
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gw_saas_config
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取  字段:gw_saas_config.id
     *
     * @return gw_saas_config.id, 
     */
    public String getId() {
        return id;
    }

    /**
     * 设置  字段:gw_saas_config.id
     *
     * @param id the value for gw_saas_config.id, 
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * 获取 接入商授权id 字段:gw_saas_config.open_id
     *
     * @return gw_saas_config.open_id, 接入商授权id
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * 设置 接入商授权id 字段:gw_saas_config.open_id
     *
     * @param openId the value for gw_saas_config.open_id, 接入商授权id
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * 获取 接入商名称 字段:gw_saas_config.open_name
     *
     * @return gw_saas_config.open_name, 接入商名称
     */
    public String getOpenName() {
        return openName;
    }

    /**
     * 设置 接入商名称 字段:gw_saas_config.open_name
     *
     * @param openName the value for gw_saas_config.open_name, 接入商名称
     */
    public void setOpenName(String openName) {
        this.openName = openName == null ? null : openName.trim();
    }

    /**
     * 获取 内部私钥 字段:gw_saas_config.private_key
     *
     * @return gw_saas_config.private_key, 内部私钥
     */
    public String getPrivateKey() {
        return privateKey;
    }

    /**
     * 设置 内部私钥 字段:gw_saas_config.private_key
     *
     * @param privateKey the value for gw_saas_config.private_key, 内部私钥
     */
    public void setPrivateKey(String privateKey) {
        this.privateKey = privateKey == null ? null : privateKey.trim();
    }

    /**
     * 获取 内部公钥 字段:gw_saas_config.public_key
     *
     * @return gw_saas_config.public_key, 内部公钥
     */
    public String getPublicKey() {
        return publicKey;
    }

    /**
     * 设置 内部公钥 字段:gw_saas_config.public_key
     *
     * @param publicKey the value for gw_saas_config.public_key, 内部公钥
     */
    public void setPublicKey(String publicKey) {
        this.publicKey = publicKey == null ? null : publicKey.trim();
    }

    /**
     * 获取 外部公钥 字段:gw_saas_config.outer_public_key
     *
     * @return gw_saas_config.outer_public_key, 外部公钥
     */
    public String getOuterPublicKey() {
        return outerPublicKey;
    }

    /**
     * 设置 外部公钥 字段:gw_saas_config.outer_public_key
     *
     * @param outerPublicKey the value for gw_saas_config.outer_public_key, 外部公钥
     */
    public void setOuterPublicKey(String outerPublicKey) {
        this.outerPublicKey = outerPublicKey == null ? null : outerPublicKey.trim();
    }

    /**
     * 获取 接入商状态，1-准入/2-禁止 字段:gw_saas_config.status
     *
     * @return gw_saas_config.status, 接入商状态，1-准入/2-禁止
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * 设置 接入商状态，1-准入/2-禁止 字段:gw_saas_config.status
     *
     * @param status the value for gw_saas_config.status, 接入商状态，1-准入/2-禁止
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * 获取 到期时间 字段:gw_saas_config.expire_time
     *
     * @return gw_saas_config.expire_time, 到期时间
     */
    public Date getExpireTime() {
        return expireTime;
    }

    /**
     * 设置 到期时间 字段:gw_saas_config.expire_time
     *
     * @param expireTime the value for gw_saas_config.expire_time, 到期时间
     */
    public void setExpireTime(Date expireTime) {
        this.expireTime = expireTime;
    }

    /**
     * 获取 0-未删除,1-已删除 字段:gw_saas_config.delete_flag
     *
     * @return gw_saas_config.delete_flag, 0-未删除,1-已删除
     */
    public Boolean getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * 设置 0-未删除,1-已删除 字段:gw_saas_config.delete_flag
     *
     * @param deleteFlag the value for gw_saas_config.delete_flag, 0-未删除,1-已删除
     */
    public void setDeleteFlag(Boolean deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * 获取 操作人 字段:gw_saas_config.operator
     *
     * @return gw_saas_config.operator, 操作人
     */
    public String getOperator() {
        return operator;
    }

    /**
     * 设置 操作人 字段:gw_saas_config.operator
     *
     * @param operator the value for gw_saas_config.operator, 操作人
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * 获取 更新时间 字段:gw_saas_config.update_time
     *
     * @return gw_saas_config.update_time, 更新时间
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * 设置 更新时间 字段:gw_saas_config.update_time
     *
     * @param updateTime the value for gw_saas_config.update_time, 更新时间
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * 获取 创建时间 字段:gw_saas_config.create_time
     *
     * @return gw_saas_config.create_time, 创建时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 设置 创建时间 字段:gw_saas_config.create_time
     *
     * @param createTime the value for gw_saas_config.create_time, 创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}