package com.cloud.askwalking.repository.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ConfigureApiExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gw_configure_api
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gw_configure_api
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gw_configure_api
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    private Integer limit;

    private Integer offset;

    /**
     *  构造查询条件,gw_configure_api
     */
    public ConfigureApiExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     *  设置排序字段,gw_configure_api
     *
     * @param orderByClause 排序字段
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     *  获取排序字段,gw_configure_api
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     *  设置过滤重复数据,gw_configure_api
     *
     * @param distinct 是否过滤重复数据
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     *  是否过滤重复数据,gw_configure_api
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     *  获取当前的查询条件实例,gw_configure_api
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * ,gw_configure_api
     *
     * @param criteria 过滤条件实例
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * ,gw_configure_api
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     *  创建一个查询条件,gw_configure_api
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     *  内部构建查询条件对象,gw_configure_api
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     *  清除查询条件,gw_configure_api
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return offset;
    }

    /**
     * gw_configure_api
     * GeneratedCriteria
     * 数据库表：gw_configure_api
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andApplicationNameIsNull() {
            addCriterion("application_name is null");
            return (Criteria) this;
        }

        public Criteria andApplicationNameIsNotNull() {
            addCriterion("application_name is not null");
            return (Criteria) this;
        }

        public Criteria andApplicationNameEqualTo(String value) {
            addCriterion("application_name =", value, "applicationName");
            return (Criteria) this;
        }

        public Criteria andApplicationNameNotEqualTo(String value) {
            addCriterion("application_name <>", value, "applicationName");
            return (Criteria) this;
        }

        public Criteria andApplicationNameGreaterThan(String value) {
            addCriterion("application_name >", value, "applicationName");
            return (Criteria) this;
        }

        public Criteria andApplicationNameGreaterThanOrEqualTo(String value) {
            addCriterion("application_name >=", value, "applicationName");
            return (Criteria) this;
        }

        public Criteria andApplicationNameLessThan(String value) {
            addCriterion("application_name <", value, "applicationName");
            return (Criteria) this;
        }

        public Criteria andApplicationNameLessThanOrEqualTo(String value) {
            addCriterion("application_name <=", value, "applicationName");
            return (Criteria) this;
        }

        public Criteria andApplicationNameLike(String value) {
            addCriterion("application_name like", value, "applicationName");
            return (Criteria) this;
        }

        public Criteria andApplicationNameNotLike(String value) {
            addCriterion("application_name not like", value, "applicationName");
            return (Criteria) this;
        }

        public Criteria andApplicationNameIn(List<String> values) {
            addCriterion("application_name in", values, "applicationName");
            return (Criteria) this;
        }

        public Criteria andApplicationNameNotIn(List<String> values) {
            addCriterion("application_name not in", values, "applicationName");
            return (Criteria) this;
        }

        public Criteria andApplicationNameBetween(String value1, String value2) {
            addCriterion("application_name between", value1, value2, "applicationName");
            return (Criteria) this;
        }

        public Criteria andApplicationNameNotBetween(String value1, String value2) {
            addCriterion("application_name not between", value1, value2, "applicationName");
            return (Criteria) this;
        }

        public Criteria andProtocolIsNull() {
            addCriterion("protocol is null");
            return (Criteria) this;
        }

        public Criteria andProtocolIsNotNull() {
            addCriterion("protocol is not null");
            return (Criteria) this;
        }

        public Criteria andProtocolEqualTo(String value) {
            addCriterion("protocol =", value, "protocol");
            return (Criteria) this;
        }

        public Criteria andProtocolNotEqualTo(String value) {
            addCriterion("protocol <>", value, "protocol");
            return (Criteria) this;
        }

        public Criteria andProtocolGreaterThan(String value) {
            addCriterion("protocol >", value, "protocol");
            return (Criteria) this;
        }

        public Criteria andProtocolGreaterThanOrEqualTo(String value) {
            addCriterion("protocol >=", value, "protocol");
            return (Criteria) this;
        }

        public Criteria andProtocolLessThan(String value) {
            addCriterion("protocol <", value, "protocol");
            return (Criteria) this;
        }

        public Criteria andProtocolLessThanOrEqualTo(String value) {
            addCriterion("protocol <=", value, "protocol");
            return (Criteria) this;
        }

        public Criteria andProtocolLike(String value) {
            addCriterion("protocol like", value, "protocol");
            return (Criteria) this;
        }

        public Criteria andProtocolNotLike(String value) {
            addCriterion("protocol not like", value, "protocol");
            return (Criteria) this;
        }

        public Criteria andProtocolIn(List<String> values) {
            addCriterion("protocol in", values, "protocol");
            return (Criteria) this;
        }

        public Criteria andProtocolNotIn(List<String> values) {
            addCriterion("protocol not in", values, "protocol");
            return (Criteria) this;
        }

        public Criteria andProtocolBetween(String value1, String value2) {
            addCriterion("protocol between", value1, value2, "protocol");
            return (Criteria) this;
        }

        public Criteria andProtocolNotBetween(String value1, String value2) {
            addCriterion("protocol not between", value1, value2, "protocol");
            return (Criteria) this;
        }

        public Criteria andContentTypeIsNull() {
            addCriterion("content_type is null");
            return (Criteria) this;
        }

        public Criteria andContentTypeIsNotNull() {
            addCriterion("content_type is not null");
            return (Criteria) this;
        }

        public Criteria andContentTypeEqualTo(String value) {
            addCriterion("content_type =", value, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeNotEqualTo(String value) {
            addCriterion("content_type <>", value, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeGreaterThan(String value) {
            addCriterion("content_type >", value, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeGreaterThanOrEqualTo(String value) {
            addCriterion("content_type >=", value, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeLessThan(String value) {
            addCriterion("content_type <", value, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeLessThanOrEqualTo(String value) {
            addCriterion("content_type <=", value, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeLike(String value) {
            addCriterion("content_type like", value, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeNotLike(String value) {
            addCriterion("content_type not like", value, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeIn(List<String> values) {
            addCriterion("content_type in", values, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeNotIn(List<String> values) {
            addCriterion("content_type not in", values, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeBetween(String value1, String value2) {
            addCriterion("content_type between", value1, value2, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeNotBetween(String value1, String value2) {
            addCriterion("content_type not between", value1, value2, "contentType");
            return (Criteria) this;
        }

        public Criteria andApiTypeIsNull() {
            addCriterion("api_type is null");
            return (Criteria) this;
        }

        public Criteria andApiTypeIsNotNull() {
            addCriterion("api_type is not null");
            return (Criteria) this;
        }

        public Criteria andApiTypeEqualTo(String value) {
            addCriterion("api_type =", value, "apiType");
            return (Criteria) this;
        }

        public Criteria andApiTypeNotEqualTo(String value) {
            addCriterion("api_type <>", value, "apiType");
            return (Criteria) this;
        }

        public Criteria andApiTypeGreaterThan(String value) {
            addCriterion("api_type >", value, "apiType");
            return (Criteria) this;
        }

        public Criteria andApiTypeGreaterThanOrEqualTo(String value) {
            addCriterion("api_type >=", value, "apiType");
            return (Criteria) this;
        }

        public Criteria andApiTypeLessThan(String value) {
            addCriterion("api_type <", value, "apiType");
            return (Criteria) this;
        }

        public Criteria andApiTypeLessThanOrEqualTo(String value) {
            addCriterion("api_type <=", value, "apiType");
            return (Criteria) this;
        }

        public Criteria andApiTypeLike(String value) {
            addCriterion("api_type like", value, "apiType");
            return (Criteria) this;
        }

        public Criteria andApiTypeNotLike(String value) {
            addCriterion("api_type not like", value, "apiType");
            return (Criteria) this;
        }

        public Criteria andApiTypeIn(List<String> values) {
            addCriterion("api_type in", values, "apiType");
            return (Criteria) this;
        }

        public Criteria andApiTypeNotIn(List<String> values) {
            addCriterion("api_type not in", values, "apiType");
            return (Criteria) this;
        }

        public Criteria andApiTypeBetween(String value1, String value2) {
            addCriterion("api_type between", value1, value2, "apiType");
            return (Criteria) this;
        }

        public Criteria andApiTypeNotBetween(String value1, String value2) {
            addCriterion("api_type not between", value1, value2, "apiType");
            return (Criteria) this;
        }

        public Criteria andRequestUriIsNull() {
            addCriterion("request_uri is null");
            return (Criteria) this;
        }

        public Criteria andRequestUriIsNotNull() {
            addCriterion("request_uri is not null");
            return (Criteria) this;
        }

        public Criteria andRequestUriEqualTo(String value) {
            addCriterion("request_uri =", value, "requestUri");
            return (Criteria) this;
        }

        public Criteria andRequestUriNotEqualTo(String value) {
            addCriterion("request_uri <>", value, "requestUri");
            return (Criteria) this;
        }

        public Criteria andRequestUriGreaterThan(String value) {
            addCriterion("request_uri >", value, "requestUri");
            return (Criteria) this;
        }

        public Criteria andRequestUriGreaterThanOrEqualTo(String value) {
            addCriterion("request_uri >=", value, "requestUri");
            return (Criteria) this;
        }

        public Criteria andRequestUriLessThan(String value) {
            addCriterion("request_uri <", value, "requestUri");
            return (Criteria) this;
        }

        public Criteria andRequestUriLessThanOrEqualTo(String value) {
            addCriterion("request_uri <=", value, "requestUri");
            return (Criteria) this;
        }

        public Criteria andRequestUriLike(String value) {
            addCriterion("request_uri like", value, "requestUri");
            return (Criteria) this;
        }

        public Criteria andRequestUriNotLike(String value) {
            addCriterion("request_uri not like", value, "requestUri");
            return (Criteria) this;
        }

        public Criteria andRequestUriIn(List<String> values) {
            addCriterion("request_uri in", values, "requestUri");
            return (Criteria) this;
        }

        public Criteria andRequestUriNotIn(List<String> values) {
            addCriterion("request_uri not in", values, "requestUri");
            return (Criteria) this;
        }

        public Criteria andRequestUriBetween(String value1, String value2) {
            addCriterion("request_uri between", value1, value2, "requestUri");
            return (Criteria) this;
        }

        public Criteria andRequestUriNotBetween(String value1, String value2) {
            addCriterion("request_uri not between", value1, value2, "requestUri");
            return (Criteria) this;
        }

        public Criteria andRequestMethodIsNull() {
            addCriterion("request_method is null");
            return (Criteria) this;
        }

        public Criteria andRequestMethodIsNotNull() {
            addCriterion("request_method is not null");
            return (Criteria) this;
        }

        public Criteria andRequestMethodEqualTo(String value) {
            addCriterion("request_method =", value, "requestMethod");
            return (Criteria) this;
        }

        public Criteria andRequestMethodNotEqualTo(String value) {
            addCriterion("request_method <>", value, "requestMethod");
            return (Criteria) this;
        }

        public Criteria andRequestMethodGreaterThan(String value) {
            addCriterion("request_method >", value, "requestMethod");
            return (Criteria) this;
        }

        public Criteria andRequestMethodGreaterThanOrEqualTo(String value) {
            addCriterion("request_method >=", value, "requestMethod");
            return (Criteria) this;
        }

        public Criteria andRequestMethodLessThan(String value) {
            addCriterion("request_method <", value, "requestMethod");
            return (Criteria) this;
        }

        public Criteria andRequestMethodLessThanOrEqualTo(String value) {
            addCriterion("request_method <=", value, "requestMethod");
            return (Criteria) this;
        }

        public Criteria andRequestMethodLike(String value) {
            addCriterion("request_method like", value, "requestMethod");
            return (Criteria) this;
        }

        public Criteria andRequestMethodNotLike(String value) {
            addCriterion("request_method not like", value, "requestMethod");
            return (Criteria) this;
        }

        public Criteria andRequestMethodIn(List<String> values) {
            addCriterion("request_method in", values, "requestMethod");
            return (Criteria) this;
        }

        public Criteria andRequestMethodNotIn(List<String> values) {
            addCriterion("request_method not in", values, "requestMethod");
            return (Criteria) this;
        }

        public Criteria andRequestMethodBetween(String value1, String value2) {
            addCriterion("request_method between", value1, value2, "requestMethod");
            return (Criteria) this;
        }

        public Criteria andRequestMethodNotBetween(String value1, String value2) {
            addCriterion("request_method not between", value1, value2, "requestMethod");
            return (Criteria) this;
        }

        public Criteria andApiInterfaceIsNull() {
            addCriterion("api_interface is null");
            return (Criteria) this;
        }

        public Criteria andApiInterfaceIsNotNull() {
            addCriterion("api_interface is not null");
            return (Criteria) this;
        }

        public Criteria andApiInterfaceEqualTo(String value) {
            addCriterion("api_interface =", value, "apiInterface");
            return (Criteria) this;
        }

        public Criteria andApiInterfaceNotEqualTo(String value) {
            addCriterion("api_interface <>", value, "apiInterface");
            return (Criteria) this;
        }

        public Criteria andApiInterfaceGreaterThan(String value) {
            addCriterion("api_interface >", value, "apiInterface");
            return (Criteria) this;
        }

        public Criteria andApiInterfaceGreaterThanOrEqualTo(String value) {
            addCriterion("api_interface >=", value, "apiInterface");
            return (Criteria) this;
        }

        public Criteria andApiInterfaceLessThan(String value) {
            addCriterion("api_interface <", value, "apiInterface");
            return (Criteria) this;
        }

        public Criteria andApiInterfaceLessThanOrEqualTo(String value) {
            addCriterion("api_interface <=", value, "apiInterface");
            return (Criteria) this;
        }

        public Criteria andApiInterfaceLike(String value) {
            addCriterion("api_interface like", value, "apiInterface");
            return (Criteria) this;
        }

        public Criteria andApiInterfaceNotLike(String value) {
            addCriterion("api_interface not like", value, "apiInterface");
            return (Criteria) this;
        }

        public Criteria andApiInterfaceIn(List<String> values) {
            addCriterion("api_interface in", values, "apiInterface");
            return (Criteria) this;
        }

        public Criteria andApiInterfaceNotIn(List<String> values) {
            addCriterion("api_interface not in", values, "apiInterface");
            return (Criteria) this;
        }

        public Criteria andApiInterfaceBetween(String value1, String value2) {
            addCriterion("api_interface between", value1, value2, "apiInterface");
            return (Criteria) this;
        }

        public Criteria andApiInterfaceNotBetween(String value1, String value2) {
            addCriterion("api_interface not between", value1, value2, "apiInterface");
            return (Criteria) this;
        }

        public Criteria andApiVersionIsNull() {
            addCriterion("api_version is null");
            return (Criteria) this;
        }

        public Criteria andApiVersionIsNotNull() {
            addCriterion("api_version is not null");
            return (Criteria) this;
        }

        public Criteria andApiVersionEqualTo(String value) {
            addCriterion("api_version =", value, "apiVersion");
            return (Criteria) this;
        }

        public Criteria andApiVersionNotEqualTo(String value) {
            addCriterion("api_version <>", value, "apiVersion");
            return (Criteria) this;
        }

        public Criteria andApiVersionGreaterThan(String value) {
            addCriterion("api_version >", value, "apiVersion");
            return (Criteria) this;
        }

        public Criteria andApiVersionGreaterThanOrEqualTo(String value) {
            addCriterion("api_version >=", value, "apiVersion");
            return (Criteria) this;
        }

        public Criteria andApiVersionLessThan(String value) {
            addCriterion("api_version <", value, "apiVersion");
            return (Criteria) this;
        }

        public Criteria andApiVersionLessThanOrEqualTo(String value) {
            addCriterion("api_version <=", value, "apiVersion");
            return (Criteria) this;
        }

        public Criteria andApiVersionLike(String value) {
            addCriterion("api_version like", value, "apiVersion");
            return (Criteria) this;
        }

        public Criteria andApiVersionNotLike(String value) {
            addCriterion("api_version not like", value, "apiVersion");
            return (Criteria) this;
        }

        public Criteria andApiVersionIn(List<String> values) {
            addCriterion("api_version in", values, "apiVersion");
            return (Criteria) this;
        }

        public Criteria andApiVersionNotIn(List<String> values) {
            addCriterion("api_version not in", values, "apiVersion");
            return (Criteria) this;
        }

        public Criteria andApiVersionBetween(String value1, String value2) {
            addCriterion("api_version between", value1, value2, "apiVersion");
            return (Criteria) this;
        }

        public Criteria andApiVersionNotBetween(String value1, String value2) {
            addCriterion("api_version not between", value1, value2, "apiVersion");
            return (Criteria) this;
        }

        public Criteria andApiRequestClassIsNull() {
            addCriterion("api_request_class is null");
            return (Criteria) this;
        }

        public Criteria andApiRequestClassIsNotNull() {
            addCriterion("api_request_class is not null");
            return (Criteria) this;
        }

        public Criteria andApiRequestClassEqualTo(String value) {
            addCriterion("api_request_class =", value, "apiRequestClass");
            return (Criteria) this;
        }

        public Criteria andApiRequestClassNotEqualTo(String value) {
            addCriterion("api_request_class <>", value, "apiRequestClass");
            return (Criteria) this;
        }

        public Criteria andApiRequestClassGreaterThan(String value) {
            addCriterion("api_request_class >", value, "apiRequestClass");
            return (Criteria) this;
        }

        public Criteria andApiRequestClassGreaterThanOrEqualTo(String value) {
            addCriterion("api_request_class >=", value, "apiRequestClass");
            return (Criteria) this;
        }

        public Criteria andApiRequestClassLessThan(String value) {
            addCriterion("api_request_class <", value, "apiRequestClass");
            return (Criteria) this;
        }

        public Criteria andApiRequestClassLessThanOrEqualTo(String value) {
            addCriterion("api_request_class <=", value, "apiRequestClass");
            return (Criteria) this;
        }

        public Criteria andApiRequestClassLike(String value) {
            addCriterion("api_request_class like", value, "apiRequestClass");
            return (Criteria) this;
        }

        public Criteria andApiRequestClassNotLike(String value) {
            addCriterion("api_request_class not like", value, "apiRequestClass");
            return (Criteria) this;
        }

        public Criteria andApiRequestClassIn(List<String> values) {
            addCriterion("api_request_class in", values, "apiRequestClass");
            return (Criteria) this;
        }

        public Criteria andApiRequestClassNotIn(List<String> values) {
            addCriterion("api_request_class not in", values, "apiRequestClass");
            return (Criteria) this;
        }

        public Criteria andApiRequestClassBetween(String value1, String value2) {
            addCriterion("api_request_class between", value1, value2, "apiRequestClass");
            return (Criteria) this;
        }

        public Criteria andApiRequestClassNotBetween(String value1, String value2) {
            addCriterion("api_request_class not between", value1, value2, "apiRequestClass");
            return (Criteria) this;
        }

        public Criteria andApiMethodIsNull() {
            addCriterion("api_method is null");
            return (Criteria) this;
        }

        public Criteria andApiMethodIsNotNull() {
            addCriterion("api_method is not null");
            return (Criteria) this;
        }

        public Criteria andApiMethodEqualTo(String value) {
            addCriterion("api_method =", value, "apiMethod");
            return (Criteria) this;
        }

        public Criteria andApiMethodNotEqualTo(String value) {
            addCriterion("api_method <>", value, "apiMethod");
            return (Criteria) this;
        }

        public Criteria andApiMethodGreaterThan(String value) {
            addCriterion("api_method >", value, "apiMethod");
            return (Criteria) this;
        }

        public Criteria andApiMethodGreaterThanOrEqualTo(String value) {
            addCriterion("api_method >=", value, "apiMethod");
            return (Criteria) this;
        }

        public Criteria andApiMethodLessThan(String value) {
            addCriterion("api_method <", value, "apiMethod");
            return (Criteria) this;
        }

        public Criteria andApiMethodLessThanOrEqualTo(String value) {
            addCriterion("api_method <=", value, "apiMethod");
            return (Criteria) this;
        }

        public Criteria andApiMethodLike(String value) {
            addCriterion("api_method like", value, "apiMethod");
            return (Criteria) this;
        }

        public Criteria andApiMethodNotLike(String value) {
            addCriterion("api_method not like", value, "apiMethod");
            return (Criteria) this;
        }

        public Criteria andApiMethodIn(List<String> values) {
            addCriterion("api_method in", values, "apiMethod");
            return (Criteria) this;
        }

        public Criteria andApiMethodNotIn(List<String> values) {
            addCriterion("api_method not in", values, "apiMethod");
            return (Criteria) this;
        }

        public Criteria andApiMethodBetween(String value1, String value2) {
            addCriterion("api_method between", value1, value2, "apiMethod");
            return (Criteria) this;
        }

        public Criteria andApiMethodNotBetween(String value1, String value2) {
            addCriterion("api_method not between", value1, value2, "apiMethod");
            return (Criteria) this;
        }

        public Criteria andApiGroupIsNull() {
            addCriterion("api_group is null");
            return (Criteria) this;
        }

        public Criteria andApiGroupIsNotNull() {
            addCriterion("api_group is not null");
            return (Criteria) this;
        }

        public Criteria andApiGroupEqualTo(String value) {
            addCriterion("api_group =", value, "apiGroup");
            return (Criteria) this;
        }

        public Criteria andApiGroupNotEqualTo(String value) {
            addCriterion("api_group <>", value, "apiGroup");
            return (Criteria) this;
        }

        public Criteria andApiGroupGreaterThan(String value) {
            addCriterion("api_group >", value, "apiGroup");
            return (Criteria) this;
        }

        public Criteria andApiGroupGreaterThanOrEqualTo(String value) {
            addCriterion("api_group >=", value, "apiGroup");
            return (Criteria) this;
        }

        public Criteria andApiGroupLessThan(String value) {
            addCriterion("api_group <", value, "apiGroup");
            return (Criteria) this;
        }

        public Criteria andApiGroupLessThanOrEqualTo(String value) {
            addCriterion("api_group <=", value, "apiGroup");
            return (Criteria) this;
        }

        public Criteria andApiGroupLike(String value) {
            addCriterion("api_group like", value, "apiGroup");
            return (Criteria) this;
        }

        public Criteria andApiGroupNotLike(String value) {
            addCriterion("api_group not like", value, "apiGroup");
            return (Criteria) this;
        }

        public Criteria andApiGroupIn(List<String> values) {
            addCriterion("api_group in", values, "apiGroup");
            return (Criteria) this;
        }

        public Criteria andApiGroupNotIn(List<String> values) {
            addCriterion("api_group not in", values, "apiGroup");
            return (Criteria) this;
        }

        public Criteria andApiGroupBetween(String value1, String value2) {
            addCriterion("api_group between", value1, value2, "apiGroup");
            return (Criteria) this;
        }

        public Criteria andApiGroupNotBetween(String value1, String value2) {
            addCriterion("api_group not between", value1, value2, "apiGroup");
            return (Criteria) this;
        }

        public Criteria andApiNameIsNull() {
            addCriterion("api_name is null");
            return (Criteria) this;
        }

        public Criteria andApiNameIsNotNull() {
            addCriterion("api_name is not null");
            return (Criteria) this;
        }

        public Criteria andApiNameEqualTo(String value) {
            addCriterion("api_name =", value, "apiName");
            return (Criteria) this;
        }

        public Criteria andApiNameNotEqualTo(String value) {
            addCriterion("api_name <>", value, "apiName");
            return (Criteria) this;
        }

        public Criteria andApiNameGreaterThan(String value) {
            addCriterion("api_name >", value, "apiName");
            return (Criteria) this;
        }

        public Criteria andApiNameGreaterThanOrEqualTo(String value) {
            addCriterion("api_name >=", value, "apiName");
            return (Criteria) this;
        }

        public Criteria andApiNameLessThan(String value) {
            addCriterion("api_name <", value, "apiName");
            return (Criteria) this;
        }

        public Criteria andApiNameLessThanOrEqualTo(String value) {
            addCriterion("api_name <=", value, "apiName");
            return (Criteria) this;
        }

        public Criteria andApiNameLike(String value) {
            addCriterion("api_name like", value, "apiName");
            return (Criteria) this;
        }

        public Criteria andApiNameNotLike(String value) {
            addCriterion("api_name not like", value, "apiName");
            return (Criteria) this;
        }

        public Criteria andApiNameIn(List<String> values) {
            addCriterion("api_name in", values, "apiName");
            return (Criteria) this;
        }

        public Criteria andApiNameNotIn(List<String> values) {
            addCriterion("api_name not in", values, "apiName");
            return (Criteria) this;
        }

        public Criteria andApiNameBetween(String value1, String value2) {
            addCriterion("api_name between", value1, value2, "apiName");
            return (Criteria) this;
        }

        public Criteria andApiNameNotBetween(String value1, String value2) {
            addCriterion("api_name not between", value1, value2, "apiName");
            return (Criteria) this;
        }

        public Criteria andApiAsyncIsNull() {
            addCriterion("api_async is null");
            return (Criteria) this;
        }

        public Criteria andApiAsyncIsNotNull() {
            addCriterion("api_async is not null");
            return (Criteria) this;
        }

        public Criteria andApiAsyncEqualTo(Boolean value) {
            addCriterion("api_async =", value, "apiAsync");
            return (Criteria) this;
        }

        public Criteria andApiAsyncNotEqualTo(Boolean value) {
            addCriterion("api_async <>", value, "apiAsync");
            return (Criteria) this;
        }

        public Criteria andApiAsyncGreaterThan(Boolean value) {
            addCriterion("api_async >", value, "apiAsync");
            return (Criteria) this;
        }

        public Criteria andApiAsyncGreaterThanOrEqualTo(Boolean value) {
            addCriterion("api_async >=", value, "apiAsync");
            return (Criteria) this;
        }

        public Criteria andApiAsyncLessThan(Boolean value) {
            addCriterion("api_async <", value, "apiAsync");
            return (Criteria) this;
        }

        public Criteria andApiAsyncLessThanOrEqualTo(Boolean value) {
            addCriterion("api_async <=", value, "apiAsync");
            return (Criteria) this;
        }

        public Criteria andApiAsyncIn(List<Boolean> values) {
            addCriterion("api_async in", values, "apiAsync");
            return (Criteria) this;
        }

        public Criteria andApiAsyncNotIn(List<Boolean> values) {
            addCriterion("api_async not in", values, "apiAsync");
            return (Criteria) this;
        }

        public Criteria andApiAsyncBetween(Boolean value1, Boolean value2) {
            addCriterion("api_async between", value1, value2, "apiAsync");
            return (Criteria) this;
        }

        public Criteria andApiAsyncNotBetween(Boolean value1, Boolean value2) {
            addCriterion("api_async not between", value1, value2, "apiAsync");
            return (Criteria) this;
        }

        public Criteria andApiReloadIsNull() {
            addCriterion("api_reload is null");
            return (Criteria) this;
        }

        public Criteria andApiReloadIsNotNull() {
            addCriterion("api_reload is not null");
            return (Criteria) this;
        }

        public Criteria andApiReloadEqualTo(Boolean value) {
            addCriterion("api_reload =", value, "apiReload");
            return (Criteria) this;
        }

        public Criteria andApiReloadNotEqualTo(Boolean value) {
            addCriterion("api_reload <>", value, "apiReload");
            return (Criteria) this;
        }

        public Criteria andApiReloadGreaterThan(Boolean value) {
            addCriterion("api_reload >", value, "apiReload");
            return (Criteria) this;
        }

        public Criteria andApiReloadGreaterThanOrEqualTo(Boolean value) {
            addCriterion("api_reload >=", value, "apiReload");
            return (Criteria) this;
        }

        public Criteria andApiReloadLessThan(Boolean value) {
            addCriterion("api_reload <", value, "apiReload");
            return (Criteria) this;
        }

        public Criteria andApiReloadLessThanOrEqualTo(Boolean value) {
            addCriterion("api_reload <=", value, "apiReload");
            return (Criteria) this;
        }

        public Criteria andApiReloadIn(List<Boolean> values) {
            addCriterion("api_reload in", values, "apiReload");
            return (Criteria) this;
        }

        public Criteria andApiReloadNotIn(List<Boolean> values) {
            addCriterion("api_reload not in", values, "apiReload");
            return (Criteria) this;
        }

        public Criteria andApiReloadBetween(Boolean value1, Boolean value2) {
            addCriterion("api_reload between", value1, value2, "apiReload");
            return (Criteria) this;
        }

        public Criteria andApiReloadNotBetween(Boolean value1, Boolean value2) {
            addCriterion("api_reload not between", value1, value2, "apiReload");
            return (Criteria) this;
        }

        public Criteria andMockResponseIsNull() {
            addCriterion("mock_response is null");
            return (Criteria) this;
        }

        public Criteria andMockResponseIsNotNull() {
            addCriterion("mock_response is not null");
            return (Criteria) this;
        }

        public Criteria andMockResponseEqualTo(String value) {
            addCriterion("mock_response =", value, "mockResponse");
            return (Criteria) this;
        }

        public Criteria andMockResponseNotEqualTo(String value) {
            addCriterion("mock_response <>", value, "mockResponse");
            return (Criteria) this;
        }

        public Criteria andMockResponseGreaterThan(String value) {
            addCriterion("mock_response >", value, "mockResponse");
            return (Criteria) this;
        }

        public Criteria andMockResponseGreaterThanOrEqualTo(String value) {
            addCriterion("mock_response >=", value, "mockResponse");
            return (Criteria) this;
        }

        public Criteria andMockResponseLessThan(String value) {
            addCriterion("mock_response <", value, "mockResponse");
            return (Criteria) this;
        }

        public Criteria andMockResponseLessThanOrEqualTo(String value) {
            addCriterion("mock_response <=", value, "mockResponse");
            return (Criteria) this;
        }

        public Criteria andMockResponseLike(String value) {
            addCriterion("mock_response like", value, "mockResponse");
            return (Criteria) this;
        }

        public Criteria andMockResponseNotLike(String value) {
            addCriterion("mock_response not like", value, "mockResponse");
            return (Criteria) this;
        }

        public Criteria andMockResponseIn(List<String> values) {
            addCriterion("mock_response in", values, "mockResponse");
            return (Criteria) this;
        }

        public Criteria andMockResponseNotIn(List<String> values) {
            addCriterion("mock_response not in", values, "mockResponse");
            return (Criteria) this;
        }

        public Criteria andMockResponseBetween(String value1, String value2) {
            addCriterion("mock_response between", value1, value2, "mockResponse");
            return (Criteria) this;
        }

        public Criteria andMockResponseNotBetween(String value1, String value2) {
            addCriterion("mock_response not between", value1, value2, "mockResponse");
            return (Criteria) this;
        }

        public Criteria andSystemGuardIsNull() {
            addCriterion("system_guard is null");
            return (Criteria) this;
        }

        public Criteria andSystemGuardIsNotNull() {
            addCriterion("system_guard is not null");
            return (Criteria) this;
        }

        public Criteria andSystemGuardEqualTo(Integer value) {
            addCriterion("system_guard =", value, "systemGuard");
            return (Criteria) this;
        }

        public Criteria andSystemGuardNotEqualTo(Integer value) {
            addCriterion("system_guard <>", value, "systemGuard");
            return (Criteria) this;
        }

        public Criteria andSystemGuardGreaterThan(Integer value) {
            addCriterion("system_guard >", value, "systemGuard");
            return (Criteria) this;
        }

        public Criteria andSystemGuardGreaterThanOrEqualTo(Integer value) {
            addCriterion("system_guard >=", value, "systemGuard");
            return (Criteria) this;
        }

        public Criteria andSystemGuardLessThan(Integer value) {
            addCriterion("system_guard <", value, "systemGuard");
            return (Criteria) this;
        }

        public Criteria andSystemGuardLessThanOrEqualTo(Integer value) {
            addCriterion("system_guard <=", value, "systemGuard");
            return (Criteria) this;
        }

        public Criteria andSystemGuardIn(List<Integer> values) {
            addCriterion("system_guard in", values, "systemGuard");
            return (Criteria) this;
        }

        public Criteria andSystemGuardNotIn(List<Integer> values) {
            addCriterion("system_guard not in", values, "systemGuard");
            return (Criteria) this;
        }

        public Criteria andSystemGuardBetween(Integer value1, Integer value2) {
            addCriterion("system_guard between", value1, value2, "systemGuard");
            return (Criteria) this;
        }

        public Criteria andSystemGuardNotBetween(Integer value1, Integer value2) {
            addCriterion("system_guard not between", value1, value2, "systemGuard");
            return (Criteria) this;
        }

        public Criteria andFlowControlRuleTypeIsNull() {
            addCriterion("flow_control_rule_type is null");
            return (Criteria) this;
        }

        public Criteria andFlowControlRuleTypeIsNotNull() {
            addCriterion("flow_control_rule_type is not null");
            return (Criteria) this;
        }

        public Criteria andFlowControlRuleTypeEqualTo(Integer value) {
            addCriterion("flow_control_rule_type =", value, "flowControlRuleType");
            return (Criteria) this;
        }

        public Criteria andFlowControlRuleTypeNotEqualTo(Integer value) {
            addCriterion("flow_control_rule_type <>", value, "flowControlRuleType");
            return (Criteria) this;
        }

        public Criteria andFlowControlRuleTypeGreaterThan(Integer value) {
            addCriterion("flow_control_rule_type >", value, "flowControlRuleType");
            return (Criteria) this;
        }

        public Criteria andFlowControlRuleTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("flow_control_rule_type >=", value, "flowControlRuleType");
            return (Criteria) this;
        }

        public Criteria andFlowControlRuleTypeLessThan(Integer value) {
            addCriterion("flow_control_rule_type <", value, "flowControlRuleType");
            return (Criteria) this;
        }

        public Criteria andFlowControlRuleTypeLessThanOrEqualTo(Integer value) {
            addCriterion("flow_control_rule_type <=", value, "flowControlRuleType");
            return (Criteria) this;
        }

        public Criteria andFlowControlRuleTypeIn(List<Integer> values) {
            addCriterion("flow_control_rule_type in", values, "flowControlRuleType");
            return (Criteria) this;
        }

        public Criteria andFlowControlRuleTypeNotIn(List<Integer> values) {
            addCriterion("flow_control_rule_type not in", values, "flowControlRuleType");
            return (Criteria) this;
        }

        public Criteria andFlowControlRuleTypeBetween(Integer value1, Integer value2) {
            addCriterion("flow_control_rule_type between", value1, value2, "flowControlRuleType");
            return (Criteria) this;
        }

        public Criteria andFlowControlRuleTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("flow_control_rule_type not between", value1, value2, "flowControlRuleType");
            return (Criteria) this;
        }

        public Criteria andQpsIsNull() {
            addCriterion("qps is null");
            return (Criteria) this;
        }

        public Criteria andQpsIsNotNull() {
            addCriterion("qps is not null");
            return (Criteria) this;
        }

        public Criteria andQpsEqualTo(Float value) {
            addCriterion("qps =", value, "qps");
            return (Criteria) this;
        }

        public Criteria andQpsNotEqualTo(Float value) {
            addCriterion("qps <>", value, "qps");
            return (Criteria) this;
        }

        public Criteria andQpsGreaterThan(Float value) {
            addCriterion("qps >", value, "qps");
            return (Criteria) this;
        }

        public Criteria andQpsGreaterThanOrEqualTo(Float value) {
            addCriterion("qps >=", value, "qps");
            return (Criteria) this;
        }

        public Criteria andQpsLessThan(Float value) {
            addCriterion("qps <", value, "qps");
            return (Criteria) this;
        }

        public Criteria andQpsLessThanOrEqualTo(Float value) {
            addCriterion("qps <=", value, "qps");
            return (Criteria) this;
        }

        public Criteria andQpsIn(List<Float> values) {
            addCriterion("qps in", values, "qps");
            return (Criteria) this;
        }

        public Criteria andQpsNotIn(List<Float> values) {
            addCriterion("qps not in", values, "qps");
            return (Criteria) this;
        }

        public Criteria andQpsBetween(Float value1, Float value2) {
            addCriterion("qps between", value1, value2, "qps");
            return (Criteria) this;
        }

        public Criteria andQpsNotBetween(Float value1, Float value2) {
            addCriterion("qps not between", value1, value2, "qps");
            return (Criteria) this;
        }

        public Criteria andAvgRtIsNull() {
            addCriterion("avg_rt is null");
            return (Criteria) this;
        }

        public Criteria andAvgRtIsNotNull() {
            addCriterion("avg_rt is not null");
            return (Criteria) this;
        }

        public Criteria andAvgRtEqualTo(Long value) {
            addCriterion("avg_rt =", value, "avgRt");
            return (Criteria) this;
        }

        public Criteria andAvgRtNotEqualTo(Long value) {
            addCriterion("avg_rt <>", value, "avgRt");
            return (Criteria) this;
        }

        public Criteria andAvgRtGreaterThan(Long value) {
            addCriterion("avg_rt >", value, "avgRt");
            return (Criteria) this;
        }

        public Criteria andAvgRtGreaterThanOrEqualTo(Long value) {
            addCriterion("avg_rt >=", value, "avgRt");
            return (Criteria) this;
        }

        public Criteria andAvgRtLessThan(Long value) {
            addCriterion("avg_rt <", value, "avgRt");
            return (Criteria) this;
        }

        public Criteria andAvgRtLessThanOrEqualTo(Long value) {
            addCriterion("avg_rt <=", value, "avgRt");
            return (Criteria) this;
        }

        public Criteria andAvgRtIn(List<Long> values) {
            addCriterion("avg_rt in", values, "avgRt");
            return (Criteria) this;
        }

        public Criteria andAvgRtNotIn(List<Long> values) {
            addCriterion("avg_rt not in", values, "avgRt");
            return (Criteria) this;
        }

        public Criteria andAvgRtBetween(Long value1, Long value2) {
            addCriterion("avg_rt between", value1, value2, "avgRt");
            return (Criteria) this;
        }

        public Criteria andAvgRtNotBetween(Long value1, Long value2) {
            addCriterion("avg_rt not between", value1, value2, "avgRt");
            return (Criteria) this;
        }

        public Criteria andMaxThreadIsNull() {
            addCriterion("max_thread is null");
            return (Criteria) this;
        }

        public Criteria andMaxThreadIsNotNull() {
            addCriterion("max_thread is not null");
            return (Criteria) this;
        }

        public Criteria andMaxThreadEqualTo(Long value) {
            addCriterion("max_thread =", value, "maxThread");
            return (Criteria) this;
        }

        public Criteria andMaxThreadNotEqualTo(Long value) {
            addCriterion("max_thread <>", value, "maxThread");
            return (Criteria) this;
        }

        public Criteria andMaxThreadGreaterThan(Long value) {
            addCriterion("max_thread >", value, "maxThread");
            return (Criteria) this;
        }

        public Criteria andMaxThreadGreaterThanOrEqualTo(Long value) {
            addCriterion("max_thread >=", value, "maxThread");
            return (Criteria) this;
        }

        public Criteria andMaxThreadLessThan(Long value) {
            addCriterion("max_thread <", value, "maxThread");
            return (Criteria) this;
        }

        public Criteria andMaxThreadLessThanOrEqualTo(Long value) {
            addCriterion("max_thread <=", value, "maxThread");
            return (Criteria) this;
        }

        public Criteria andMaxThreadIn(List<Long> values) {
            addCriterion("max_thread in", values, "maxThread");
            return (Criteria) this;
        }

        public Criteria andMaxThreadNotIn(List<Long> values) {
            addCriterion("max_thread not in", values, "maxThread");
            return (Criteria) this;
        }

        public Criteria andMaxThreadBetween(Long value1, Long value2) {
            addCriterion("max_thread between", value1, value2, "maxThread");
            return (Criteria) this;
        }

        public Criteria andMaxThreadNotBetween(Long value1, Long value2) {
            addCriterion("max_thread not between", value1, value2, "maxThread");
            return (Criteria) this;
        }

        public Criteria andSignCheckIsNull() {
            addCriterion("sign_check is null");
            return (Criteria) this;
        }

        public Criteria andSignCheckIsNotNull() {
            addCriterion("sign_check is not null");
            return (Criteria) this;
        }

        public Criteria andSignCheckEqualTo(Integer value) {
            addCriterion("sign_check =", value, "signCheck");
            return (Criteria) this;
        }

        public Criteria andSignCheckNotEqualTo(Integer value) {
            addCriterion("sign_check <>", value, "signCheck");
            return (Criteria) this;
        }

        public Criteria andSignCheckGreaterThan(Integer value) {
            addCriterion("sign_check >", value, "signCheck");
            return (Criteria) this;
        }

        public Criteria andSignCheckGreaterThanOrEqualTo(Integer value) {
            addCriterion("sign_check >=", value, "signCheck");
            return (Criteria) this;
        }

        public Criteria andSignCheckLessThan(Integer value) {
            addCriterion("sign_check <", value, "signCheck");
            return (Criteria) this;
        }

        public Criteria andSignCheckLessThanOrEqualTo(Integer value) {
            addCriterion("sign_check <=", value, "signCheck");
            return (Criteria) this;
        }

        public Criteria andSignCheckIn(List<Integer> values) {
            addCriterion("sign_check in", values, "signCheck");
            return (Criteria) this;
        }

        public Criteria andSignCheckNotIn(List<Integer> values) {
            addCriterion("sign_check not in", values, "signCheck");
            return (Criteria) this;
        }

        public Criteria andSignCheckBetween(Integer value1, Integer value2) {
            addCriterion("sign_check between", value1, value2, "signCheck");
            return (Criteria) this;
        }

        public Criteria andSignCheckNotBetween(Integer value1, Integer value2) {
            addCriterion("sign_check not between", value1, value2, "signCheck");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIsNull() {
            addCriterion("delete_flag is null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIsNotNull() {
            addCriterion("delete_flag is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagEqualTo(Boolean value) {
            addCriterion("delete_flag =", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotEqualTo(Boolean value) {
            addCriterion("delete_flag <>", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagGreaterThan(Boolean value) {
            addCriterion("delete_flag >", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagGreaterThanOrEqualTo(Boolean value) {
            addCriterion("delete_flag >=", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagLessThan(Boolean value) {
            addCriterion("delete_flag <", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagLessThanOrEqualTo(Boolean value) {
            addCriterion("delete_flag <=", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIn(List<Boolean> values) {
            addCriterion("delete_flag in", values, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotIn(List<Boolean> values) {
            addCriterion("delete_flag not in", values, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagBetween(Boolean value1, Boolean value2) {
            addCriterion("delete_flag between", value1, value2, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotBetween(Boolean value1, Boolean value2) {
            addCriterion("delete_flag not between", value1, value2, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andOperatorIsNull() {
            addCriterion("operator is null");
            return (Criteria) this;
        }

        public Criteria andOperatorIsNotNull() {
            addCriterion("operator is not null");
            return (Criteria) this;
        }

        public Criteria andOperatorEqualTo(String value) {
            addCriterion("operator =", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotEqualTo(String value) {
            addCriterion("operator <>", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorGreaterThan(String value) {
            addCriterion("operator >", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorGreaterThanOrEqualTo(String value) {
            addCriterion("operator >=", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorLessThan(String value) {
            addCriterion("operator <", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorLessThanOrEqualTo(String value) {
            addCriterion("operator <=", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorLike(String value) {
            addCriterion("operator like", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotLike(String value) {
            addCriterion("operator not like", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorIn(List<String> values) {
            addCriterion("operator in", values, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotIn(List<String> values) {
            addCriterion("operator not in", values, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorBetween(String value1, String value2) {
            addCriterion("operator between", value1, value2, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotBetween(String value1, String value2) {
            addCriterion("operator not between", value1, value2, "operator");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * 类注释
     * Criteria
     * 数据库表：gw_configure_api
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * gw_configure_api
     * Criterion
     * 数据库表：gw_configure_api
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}